# Generated by Django 6.0.4 on 2026-08-12 04:34

import django.db.models.deletion
import siwak.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQMentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=300)),
                ('jawaban', models.TextField()),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ Mentoring',
                'verbose_name_plural': 'FAQ Mentoring',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='GaleriFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='siwak/galeri/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Foto Galeri',
                'verbose_name_plural': 'Galeri',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='KetuaSiwak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Fungsionaris')),
                ('tahun', models.CharField(max_length=9, verbose_name='Tahun (mis. 2025 atau 2024/2025)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='siwak/ketua/')),
                ('urutan', models.IntegerField(default=0, help_text='Angka lebih kecil tampil lebih dulu.')),
            ],
            options={
                'verbose_name': 'Ketua SIWAK-NG',
                'verbose_name_plural': 'Ketua SIWAK-NG dari Tahun ke Tahun',
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Mentor',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='MentoringBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100, verbose_name='Judul Benefit')),
                ('deskripsi', models.TextField()),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Benefit Mentoring',
                'verbose_name_plural': 'Benefit Mentoring',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='MentoringTujuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100, verbose_name='Judul Tujuan')),
                ('deskripsi', models.TextField()),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tujuan Mentoring',
                'verbose_name_plural': 'Tujuan Mentoring',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='SistemMentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField(verbose_name='Poin Sistem Mentoring')),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sistem Mentoring',
                'verbose_name_plural': 'Sistem Mentoring',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='SiwakEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('pre_event', 'Pre-Event SIWAK'), ('main_event', 'Main Event SIWAK')], max_length=20, unique=True)),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=200)),
                ('rsvp_dibuka', models.BooleanField(default=True, verbose_name='RSVP dibuka')),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SIWAK Event',
                'ordering': ['urutan', 'tanggal'],
            },
        ),
        migrations.CreateModel(
            name='SiwakInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_judul', models.CharField(default='SIWAK-NG', max_length=200)),
                ('hero_deskripsi', models.TextField(blank=True)),
                ('apa_itu_deskripsi', models.TextField(blank=True, verbose_name="Deskripsi 'Apa itu SIWAK-NG'")),
                ('apa_itu_gambar', models.ImageField(blank=True, null=True, upload_to='siwak/info/', verbose_name="Gambar 'Apa itu SIWAK-NG'")),
                ('mentoring_deskripsi', models.TextField(blank=True, verbose_name="Deskripsi 'Apa itu Mentoring'")),
                ('cta_mentoring_link', models.CharField(blank=True, default='/siwak/kelompok/', max_length=300, verbose_name="Link tombol 'Lihat Kelompok Mentoring'")),
                ('kontak_cp', models.CharField(blank=True, help_text='Link WhatsApp/kontak CP Fakultas, ditampilkan saat kelompok tidak ditemukan.', max_length=300, verbose_name='Link CP Fakultas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Info SIWAK (konten halaman utama)',
                'verbose_name_plural': 'Info SIWAK (konten halaman utama)',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul')),
                ('deskripsi', models.TextField(blank=True)),
                ('kategori', models.CharField(choices=[('pembagian_kelompok', 'Pembagian Kelompok'), ('mentoring', 'Timeline Mentoring & Pengumpulan Tugas'), ('pre_event', 'Pre-Main Event'), ('main_event', 'Main Event')], default='mentoring', max_length=30)),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(blank=True, help_text='Kosongkan jika event hanya berlangsung 1 hari.', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Timeline SIWAK',
                'ordering': ['tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_tugas', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, verbose_name='Ukuran file maksimum (MB)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tugas',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='MabaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npm', models.CharField(max_length=20, unique=True, verbose_name='NPM')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('jurusan', models.CharField(choices=[('IK', 'Ilmu Komputer'), ('SI', 'Sistem Informasi'), ('IK-IUP', 'Ilmu Komputer (International Undergraduate Program)'), ('SI-IUP', 'Sistem Informasi (International Undergraduate Program)')], max_length=10, verbose_name='Jurusan')),
                ('angkatan', models.CharField(blank=True, max_length=4, verbose_name='Angkatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maba_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Maba',
                'verbose_name_plural': 'Profil Maba',
            },
        ),
        migrations.CreateModel(
            name='KelompokMentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelompok', models.CharField(max_length=100, verbose_name='Nama Kelompok')),
                ('link_grup', models.URLField(blank=True, verbose_name='Link Grup WhatsApp')),
                ('kapasitas', models.PositiveIntegerField(default=15, verbose_name='Kapasitas')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentors', models.ManyToManyField(blank=True, related_name='kelompok_list', to='siwak.mentor', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Kelompok Mentoring',
                'verbose_name_plural': 'Kelompok Mentoring',
                'ordering': ['nama_kelompok'],
            },
        ),
        migrations.CreateModel(
            name='PesertaMentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('jurusan', models.CharField(choices=[('IK', 'Ilmu Komputer'), ('SI', 'Sistem Informasi'), ('IK-IUP', 'Ilmu Komputer (International Undergraduate Program)'), ('SI-IUP', 'Sistem Informasi (International Undergraduate Program)')], max_length=10)),
                ('npm', models.CharField(blank=True, max_length=20, verbose_name='NPM (opsional)')),
                ('kelompok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peserta_list', to='siwak.kelompokmentoring')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peserta_mentoring', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peserta Mentoring',
                'verbose_name_plural': 'Peserta Mentoring',
                'ordering': ['nama_lengkap'],
                'indexes': [models.Index(fields=['nama_lengkap', 'jurusan'], name='siwak_peser_nama_le_a049fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.CharField(blank=True, max_length=300, verbose_name='Catatan tambahan (opsional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_registrasi_token', models.CharField(default=siwak.models._new_token, editable=False, max_length=64, unique=True)),
                ('status_kehadiran', models.CharField(choices=[('registered', 'Registered'), ('hadir', 'Hadir')], default='registered', max_length=12)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('qr_kupon_token', models.CharField(default=siwak.models._new_token, editable=False, max_length=64, unique=True)),
                ('status_kupon', models.CharField(choices=[('unused', 'Unused'), ('redeemed', 'Redeemed')], default='unused', max_length=10)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_list', to='siwak.siwakevent')),
            ],
            options={
                'verbose_name': 'RSVP Event',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TugasSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=siwak.models.tugas_upload_path)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('late', 'Late')], default='submitted', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='siwak.tugas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission Tugas',
                'unique_together': {('tugas', 'user')},
            },
        ),
    ]
