# Generated by Django 6.0.4 on 2026-08-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mabaprofile',
            name='jurusan',
            field=models.CharField(choices=[('IK', 'Ilmu Komputer'), ('SI', 'Sistem Informasi'), ('KA', 'Kecerdasan Artifisial'), ('IK-IUP', 'Ilmu Komputer (International Undergraduate Program)'), ('SI-IUP', 'Sistem Informasi (International Undergraduate Program)')], max_length=10, verbose_name='Jurusan'),
        ),
        migrations.AlterField(
            model_name='pesertamentoring',
            name='jurusan',
            field=models.CharField(choices=[('IK', 'Ilmu Komputer'), ('SI', 'Sistem Informasi'), ('KA', 'Kecerdasan Artifisial'), ('IK-IUP', 'Ilmu Komputer (International Undergraduate Program)'), ('SI-IUP', 'Sistem Informasi (International Undergraduate Program)')], max_length=10),
        ),
    ]
