# Generated by Django 6.0.4 on 2026-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0002_alter_mabaprofile_jurusan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siwakevent',
            name='tipe',
        ),
        migrations.AddField(
            model_name='siwakevent',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='siwak/events/'),
        ),
    ]
