# Generated by Django 6.0.4 on 2026-09-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0003_remove_siwakevent_tipe_siwakevent_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('tipe', models.CharField(choices=[('text', 'Text'), ('choice', 'Choice'), ('file', 'File')], max_length=10)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='siwak.tugas')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.CharField(max_length=300)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='siwak.question')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='siwak/jawaban/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='siwak.tugassubmission')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='siwak.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='siwak.question')),
            ],
            options={
                'verbose_name': 'Jawaban Tugas',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
