# Generated by Django 6.0.4 on 2026-09-19 00:44

import siwak.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0003_remove_siwakevent_tipe_siwakevent_gambar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrsvp',
            old_name='catatan',
            new_name='alasan_izin',
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='kehadiran',
            field=models.CharField(choices=[('hadir', 'Hadir'), ('tidak_hadir', 'Tidak Hadir'), ('izin', 'Izin')], default='hadir', max_length=12),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='qr_kupon_token',
            field=models.CharField(default=siwak.models._new_token, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='qr_registrasi_token',
            field=models.CharField(default=siwak.models._new_token, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='status_kehadiran',
            field=models.CharField(choices=[('unused', 'Unused'), ('redeemed', 'Redeemed')], default='unused', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='status_kupon',
            field=models.CharField(choices=[('unused', 'Unused'), ('redeemed', 'Redeemed')], default='unused', max_length=10, null=True),
        ),
    ]
