# Generated by Django 6.0.4 on 2026-09-19 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0005_alter_eventrsvp_status_kehadiran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pesertamentoring',
            name='maba',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peserta', to='siwak.mabaprofile', verbose_name='Maba'),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='alasan_izin',
            field=models.CharField(blank=True, max_length=300, verbose_name='Jika Izin, Alasannya Kenapa?'),
        ),
        migrations.AlterField(
            model_name='mabaprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Terisi otomatis saat maba login lewat SSO UI. Boleh kosong.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maba_profile', to=settings.AUTH_USER_MODEL, verbose_name='Akun login'),
        ),
    ]
