# Generated by Django 6.0.4 on 2026-09-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0006_mentor_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrsvp',
            name='alasan_izin',
            field=models.CharField(blank=True, max_length=300, verbose_name='Jika Izin, Alasannya Kenapa?'),
        ),
    ]
