# Generated by Django 6.0.4 on 2026-09-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0007_pindahkan_identitas_peserta_ke_mabaprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesertamentoring',
            options={'ordering': ['maba__nama_lengkap'], 'verbose_name': 'Peserta Mentoring', 'verbose_name_plural': 'Peserta Mentoring'},
        ),
        migrations.RemoveIndex(
            model_name='pesertamentoring',
            name='siwak_peser_nama_le_a049fd_idx',
        ),
        migrations.RemoveField(
            model_name='siwakinfo',
            name='cta_mentoring_link',
        ),
        migrations.RemoveField(
            model_name='siwakinfo',
            name='hero_deskripsi',
        ),
        migrations.AlterField(
            model_name='pesertamentoring',
            name='kelompok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peserta_list', to='siwak.kelompokmentoring', verbose_name='Kelompok'),
        ),
        migrations.AlterField(
            model_name='pesertamentoring',
            name='maba',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peserta', to='siwak.mabaprofile', verbose_name='Maba'),
        ),
        migrations.RemoveField(
            model_name='pesertamentoring',
            name='jurusan',
        ),
        migrations.RemoveField(
            model_name='pesertamentoring',
            name='nama_lengkap',
        ),
        migrations.RemoveField(
            model_name='pesertamentoring',
            name='npm',
        ),
        migrations.RemoveField(
            model_name='pesertamentoring',
            name='user',
        ),
    ]
