# Generated by Django 6.0.4 on 2026-09-19 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0008_alter_pesertamentoring_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='kelompok',
            field=models.ForeignKey(blank=True, help_text='Satu mentor hanya boleh memegang satu kelompok. Boleh dikosongkan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_list', to='siwak.kelompokmentoring', verbose_name='Kelompok'),
        ),
    ]
