# Generated by Django 6.0.4 on 2026-09-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0010_pindahkan_mentor_ke_satu_kelompok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelompokmentoring',
            name='mentors',
        ),
    ]
