# Generated by Django 6.0.4 on 2026-09-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0004_question_choice_answer'),
        ('siwak', '0011_hapus_m2m_mentor_kelompok'),
    ]

    operations = [
    ]
