# Generated by Django 6.0.4 on 2026-09-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0016_hapus_mentor_dan_peserta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswaprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('mentee', 'Mentee'), ('mentor', 'Mentor')], default=None, max_length=10, null=True, verbose_name='Peran'),
        ),
    ]
