# Generated by Django 6.0.4 on 2026-09-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0017_mahasiswaprofile_role_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siwakinfo',
            name='kontak_cp',
            field=models.CharField(blank=True, help_text='Link WhatsApp/kontak CP SIWAK, ditampilkan saat kelompok tidak ditemukan.', max_length=300, verbose_name='Link CP SIWAK'),
        ),
    ]
