# Generated by Django 6.0.4 on 2026-09-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0018_alter_siwakinfo_kontak_cp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tugassubmission',
            name='file',
        ),
    ]
