# Generated by Django 6.0.4 on 2026-09-21 08:24

import django.db.models.deletion
import siwak.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0021_profile_dan_akun_lokal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPTertunda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kehadiran', models.CharField(choices=[('hadir', 'Hadir'), ('tidak_hadir', 'Tidak Hadir'), ('izin', 'Izin')], default='hadir', max_length=12)),
                ('alasan_izin', models.CharField(blank=True, max_length=300)),
                ('qr_registrasi_token', models.CharField(default=siwak.models._new_token, editable=False, max_length=64, unique=True)),
                ('qr_kupon_token', models.CharField(default=siwak.models._new_token, editable=False, max_length=64, unique=True)),
                ('dikirim_pada', models.DateTimeField(blank=True, help_text='Waktu submit di form asal; jadi `created_at` RSVP.', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_tertunda', to='siwak.siwakevent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_tertunda', to='siwak.profile')),
            ],
            options={
                'verbose_name': 'RSVP Tertunda',
                'verbose_name_plural': 'RSVP Tertunda',
                'unique_together': {('event', 'profile')},
            },
        ),
    ]
