# Generated by Django 6.0.4 on 2026-09-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0021_profile_dan_akun_lokal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrsvp',
            options={'permissions': [('pindai_registrasi', 'Bisa memindai QR registrasi ulang (gatekeeper)'), ('pindai_kupon', 'Bisa memindai QR kupon makan (konsumsi)')], 'verbose_name': 'RSVP Event'},
        ),
    ]
