# Generated by Django 6.0.4 on 2026-09-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0022_izin_pindai_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Hanya terlihat oleh pengurus dan mentor kelompok mentee ini.', verbose_name='Catatan privat'),
        ),
    ]
