# Generated by Django 6.0.4 on 2026-09-25 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0022_rsvp_tertunda'),
        ('siwak', '0023_profile_notes'),
    ]

    operations = [
    ]
