# Generated by Django 6.0.4 on 2026-09-26 02:18

from django.db import migrations, models


def hapus_review_tanpa_feedback(apps, schema_editor):
    # Review yang hanya berisi nilai tidak menyisakan apa-apa setelah kolom
    # `score` dibuang; tanpa ini mentee melihat kartu feedback kosong dan
    # submission-nya terhitung "sudah ada feedback".
    AssignmentReview = apps.get_model("siwak", "AssignmentReview")
    AssignmentReview.objects.filter(feedback__regex=r"^\s*$").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('siwak', '0024_merge_0022_rsvp_tertunda_0023_profile_notes'),
    ]

    operations = [
        migrations.RunPython(hapus_review_tanpa_feedback, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='assignmentreview',
            options={'verbose_name': 'Feedback Tugas', 'verbose_name_plural': 'Feedback Tugas'},
        ),
        migrations.RemoveField(
            model_name='assignmentreview',
            name='score',
        ),
        migrations.AlterField(
            model_name='assignmentreview',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='AssignmentReviewHistory',
        ),
    ]
