# Generated by Django 6.0.4 on 2026-09-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Kegiatan')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='activity/', verbose_name='Gambar')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tampilkan')),
            ],
            options={
                'verbose_name': 'Activity (Beranda)',
                'verbose_name_plural': 'Activity (Beranda)',
                'ordering': ['urutan', 'judul'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='company_profile/', verbose_name='Thumbnail')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Link Video')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tampilkan')),
            ],
            options={
                'verbose_name': 'Company Profile (Beranda)',
                'verbose_name_plural': 'Company Profile (Beranda)',
                'ordering': ['urutan', 'judul'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Episode')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='podcast/', verbose_name='Thumbnail')),
                ('link', models.URLField(blank=True, help_text="Tautan Spotify/YouTube untuk tombol 'Dengarkan Sekarang'.", max_length=500, verbose_name='Link Episode')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tampilkan')),
            ],
            options={
                'verbose_name': 'Podcast (Beranda)',
                'verbose_name_plural': 'Podcast (Beranda)',
                'ordering': ['urutan', 'judul'],
            },
        ),
        migrations.CreateModel(
            name='TentangFuki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Apa Itu Fuki?', max_length=200, verbose_name='Judul Section')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Tentang FUKI (Beranda)',
                'verbose_name_plural': 'Tentang FUKI (Beranda)',
            },
        ),
        migrations.CreateModel(
            name='TentangFukiGambar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='tentang_fuki/', verbose_name='Gambar')),
                ('alt', models.CharField(blank=True, help_text='Deskripsi singkat gambar untuk pembaca layar dan SEO.', max_length=200, verbose_name='Teks Alternatif')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('tentang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar_set', to='main.tentangfuki')),
            ],
            options={
                'verbose_name': 'Gambar Tentang FUKI',
                'verbose_name_plural': 'Gambar Tentang FUKI',
                'ordering': ['urutan', 'id'],
            },
        ),
    ]
