# Generated by Django 5.2.5 on 2025-08-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Jam Selesai'),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Jam Mulai'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='deskripsi',
            field=models.TextField(blank=True, verbose_name='Deskripsi Kegiatan'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='judul',
            field=models.CharField(max_length=200, verbose_name='Judul Kegiatan'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='lokasi',
            field=models.CharField(max_length=200, verbose_name='Lokasi Kegiatan'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='tanggal',
            field=models.DateField(verbose_name='Tanggal Kegiatan'),
        ),
    ]
