# Generated by Django 5.2.5 on 2025-08-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0002_kegiatan_end_time_kegiatan_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='guest_star',
            field=models.CharField(null=True, verbose_name='Guest Star Kegiatan'),
        ),
    ]
