# Generated by Django 5.2.5 on 2025-08-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0003_kegiatan_guest_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='contact',
            field=models.CharField(null=True, verbose_name='Contact Kegiatan'),
        ),
    ]
