# Generated by Django 5.2.5 on 2025-08-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0004_kegiatan_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='link',
            field=models.CharField(null=True, verbose_name='Link pendaftaran kegiatan'),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='link_lokasi',
            field=models.CharField(null=True, verbose_name='Link lokasi kegiatan'),
        ),
    ]
