# Generated by Django 5.2.5 on 2025-08-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0005_kegiatan_link_kegiatan_link_lokasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatan',
            name='link',
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='link_registrasi',
            field=models.CharField(blank=True, null=True, verbose_name='Link pendaftaran kegiatan'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='link_lokasi',
            field=models.CharField(blank=True, null=True, verbose_name='Link lokasi kegiatan'),
        ),
    ]
