# Generated by Django 6.0.4 on 2026-09-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0006_remove_kegiatan_link_kegiatan_link_registrasi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kegiatan',
            options={'ordering': ['tanggal']},
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='kegiatan/', verbose_name='Gambar Kegiatan'),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='kategori',
            field=models.CharField(choices=[('maba', 'Kegiatan Maba'), ('kajian', 'Kajian & Syiar'), ('sosial', 'Sosial'), ('internal', 'Internal')], default='kajian', max_length=20, verbose_name='Kategori Kegiatan'),
        ),
    ]
