# Generated by Django 6.0.4 on 2026-10-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdep', '0005_foto_path_ganti_foto'),
        ('kegiatan', '0007_alter_kegiatan_options_kegiatan_gambar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatan',
            name='gambar',
        ),
        migrations.RemoveField(
            model_name='kegiatan',
            name='guest_star',
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='birdep',
            field=models.ForeignKey(blank=True, help_text='Wajib diisi bila penyelenggaranya Biro / Departemen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kegiatan_set', to='birdep.birdep', verbose_name='Biro / Departemen'),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='tipe',
            field=models.CharField(choices=[('fuki', 'FUKI / General'), ('siwak', 'SIWAK'), ('birdep', 'Biro / Departemen')], default='fuki', max_length=10, verbose_name='Penyelenggara Kegiatan'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='contact',
            field=models.CharField(blank=True, null=True, verbose_name='Contact Kegiatan'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Selesai'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='lokasi',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lokasi Kegiatan'),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Mulai'),
        ),
    ]
