# Generated by Django 5.2.8 on 2025-12-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kajian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('penceramah', models.CharField(help_text='Nama Ustaz/Pembicara', max_length=255)),
                ('tanggal', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='kajian/')),
                ('deskripsi', models.TextField(help_text='Isi lengkap artikel kajian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kajian',
                'verbose_name_plural': 'Daftar Kajian',
                'ordering': ['-tanggal'],
            },
        ),
    ]
