"""
Django settings for web_fuki project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
import requests
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

def _csv_env(name, default):
    """Read a comma-separated env var, falling back to `default` when unset/empty."""
    raw = os.getenv(name, '')
    values = [item.strip() for item in raw.split(',') if item.strip()]
    return values or default


_LOOPBACK_HOSTS = ["localhost", "127.0.0.1"]

# Set via the ALLOWED_HOSTS secret in CI/CD. The fallback covers a missing secret,
# which would otherwise 400 every request.
ALLOWED_HOSTS = _csv_env('ALLOWED_HOSTS', ["fuki.cs.ui.ac.id"])

# The deploy health check runs on the VPS itself as `curl http://localhost:<port>/health/`
# and nginx forwards that Host verbatim, so Django sees `localhost`. These are
# appended unconditionally: setting the secret to just the public domain -- the
# obvious thing to do -- would make Django answer 400 and mark an otherwise
# healthy deploy as failed, after the migration had already run.
ALLOWED_HOSTS += [h for h in _LOOPBACK_HOSTS if h not in ALLOWED_HOSTS]

# nginx terminates the connection and proxies to gunicorn, so Django has to be
# told which header carries the original scheme. Without this, request.is_secure()
# is always False and CSRF rejects POSTs once TLS is added in front.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = _csv_env(
    'CSRF_TRUSTED_ORIGINS',
    [f'https://{host}' for host in ALLOWED_HOSTS if host not in _LOOPBACK_HOSTS],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django_cas_ng',
    'storages',
    'main',
    'kegiatan',
    'birdep',
    'profil',
    'blog_kajian',
    'siwak',
]

# 5.1 (Submission Rules: "File size limit"). Applies to every upload in the
# project; SIWAK task uploads additionally enforce a per-Tugas limit in
# siwak/forms.py::validate_tugas_file.
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

# 7 — Authentication: where @login_required sends anonymous users, and where
# they land after logging in.

AUTHENTICATION_BACKENDS = [
    'django_cas_ng.backends.CASBackend',
    'django.contrib.auth.backends.ModelBackend',
]

CAS_SERVER_URL = "https://sso.ui.ac.id/cas2/"
CAS_VERSION = 2

CAS_ADMIN_REDIRECT = False
CAS_LOGIN_URL_NAME = "siwak:cas_ng_login"
CAS_LOGOUT_URL_NAME = "siwak:cas_ng_logout"
CAS_LOGIN_MSG = None

# Halaman pemilih metode, bukan langsung CAS: sejak ada mentor non-SSO, user
# anonim yang membuka halaman ber-@login_required belum tentu punya akun SSO.
LOGIN_URL = "siwak:login"
CAS_REDIRECT_URL = "siwak:tugas_list"
CAS_IGNORE_REFERER = True
CAS_LOGOUT_NEXT_PAGE = "/"

# nginx di depan SSO UI menolak User-Agent default `python-requests/*`
# (HTTP 400 -> halaman HTML yang membuat parser python-cas melempar
# ParseError). Kirim serviceValidate pakai User-Agent browser supaya WAF SSO UI
# menerimanya dan mengembalikan XML CAS yang valid.
def _cas_session_factory():
    session = requests.Session()
    session.headers['User-Agent'] = (
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
        '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    )
    return session


CAS_SESSION_FACTORY = _cas_session_factory

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must sit directly below SecurityMiddleware so static files are
    # served without paying for the rest of the middleware stack.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Halaman 403 "Akses Ditolak" SIWAK untuk user yang salah peran (siwak/akses.py).
    'siwak.akses.AksesDitolakMiddleware',
]

ROOT_URLCONF = 'web_fuki.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Menyuplai SITE_NAME/SITE_URL/SEO_* ke setiap template supaya
                # base.html bisa menyusun <title>, canonical, Open Graph, dan JSON-LD
                # dari satu sumber saja.
                'main.context_processors.seo',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_fuki.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Driven by DB_HOST rather than a PRODUCTION toggle: the old flag meant a single
# forgotten env var silently pointed the container at its own localhost. Discrete
# vars are also safer than DATABASE_URL, which requires URL-encoding any password
# containing @ / : or #. DATABASE_URL is still honoured for a managed DB later.
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(os.environ['DATABASE_URL'], conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': 600,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT deliberately differs from the source `static/` directory. When they
# were the same path, the production volume mounted over /app/static was only ever
# seeded from the image on first creation -- so any later edit to a file in
# static/ never reached the server again. Collecting into a separate directory
# means every deploy rewrites it.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Uploaded media uses S3 when a bucket is configured; local development can
# leave the bucket empty to keep using MEDIA_ROOT.
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'ap-southeast-3')
# Presigned URLs must use the regional endpoint. The global endpoint rejects
# Jakarta bucket downloads with IllegalLocationConstraintException.
AWS_S3_ENDPOINT_URL = f'https://s3.{AWS_S3_REGION_NAME}.amazonaws.com'
AWS_S3_ADDRESSING_STYLE = 'virtual'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = False

STORAGES = {
    'default': {
        'BACKEND': (
            'storages.backends.s3.S3Storage' if AWS_STORAGE_BUCKET_NAME
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        # The old STATICFILES_STORAGE setting was removed in Django 5.1, so on
        # Django 6 it was silently ignored and WhiteNoise was never actually
        # active. Plain compression (not the manifest variant) is used so a stale
        # {% static %} reference cannot hard-fail collectstatic and crash-loop the
        # container on deploy.
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
            else 'whitenoise.storage.CompressedStaticFilesStorage'
        ),
    },
}

# Unit tests must never use production media storage, even when the developer's
# .env contains AWS_STORAGE_BUCKET_NAME.  InMemoryStorage keeps uploads local
# to the test process and avoids both network calls and leftover media files.
RUNNING_TESTS = "test" in sys.argv[1:]
if RUNNING_TESTS:
    STORAGES["default"] = {
        "BACKEND": "django.core.files.storage.InMemoryStorage",
    }


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ---------------------------------------------------------------------------
# SEO
# ---------------------------------------------------------------------------
# Satu-satunya sumber kebenaran untuk metadata situs. Dipakai oleh
# main/context_processors.py (untuk <title>, meta description, canonical,
# Open Graph, dan JSON-LD di templates/base.html) serta oleh
# web_fuki/sitemaps.py. Ubah di sini, bukan di masing-masing template.

SITE_NAME = 'FUKI Fasilkom UI'

# Dipakai untuk menyusun URL absolut (canonical, og:image, JSON-LD, sitemap).
# Harus tanpa garis miring di akhir.
SITE_URL = os.getenv('SITE_URL', 'https://fuki.cs.ui.ac.id').rstrip('/')

# Judul halaman depan. Sengaja tidak memakai sufiks " | FUKI Fasilkom UI"
# karena nama merek sudah ada di depan.
SITE_TITLE = 'FUKI Fasilkom UI — Forum Ukhuwah dan Kajian Islam'

# Meta description bawaan. Dijaga di bawah ~160 karakter supaya tidak
# dipotong Google di halaman hasil pencarian.
SITE_DESCRIPTION = (
    'FUKI Fasilkom UI, Forum Ukhuwah dan Kajian Islam, adalah Lembaga Dakwah '
    'Kampus Fakultas Ilmu Komputer Universitas Indonesia. Info kajian, '
    'kegiatan, dan mentoring.'
)

# Gambar bawaan untuk pratinjau saat tautan dibagikan (Open Graph / Twitter).
SITE_OG_IMAGE = 'images/Logo-FUKI.png'

# Akun resmi. Masuk ke properti `sameAs` pada JSON-LD Organization — inilah
# yang dipakai Google untuk mengaitkan situs ini dengan entitas "FUKI".
SITE_SOCIAL_PROFILES = [
    'https://www.instagram.com/fukifasilkom/',
    'https://www.youtube.com/@fukifasilkomui',
    'https://x.com/fukifasilkom',
]

# Token verifikasi kepemilikan domain dari Google Search Console.
GOOGLE_SITE_VERIFICATION = os.getenv(
    'GOOGLE_SITE_VERIFICATION',
    'lCewhFlHG9UyyEKQPRpfzDkunjEQRLb1J0Bc9FgL3Xo',
)


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
# Logger "cas" di level DEBUG menampilkan respons mentah serviceValidate dari
# SSO UI (termasuk bagian XML yang rusak) sebelum parser toleran di
# siwak/sso.py bekerja. Root tetap WARNING seperti bawaan Django.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {'format': '{asctime} {levelname} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'console'},
    },
    'root': {'handlers': ['console'], 'level': 'WARNING'},
    'loggers': {
        'cas': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False},
    },
}
