# Generated by Django 5.2.5 on 2025-08-12 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama BirDep')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo_filename', models.CharField(max_length=100, verbose_name='Nama File Logo')),
                ('tentang_deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Tentang')),
                ('tugas', models.TextField(blank=True, verbose_name='Tugas')),
                ('tanggung_jawab', models.TextField(blank=True, verbose_name='Tanggung Jawab')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
            ],
            options={
                'verbose_name': 'BirDep',
                'verbose_name_plural': 'BirDeps',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Fungsionaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('jabatan', models.CharField(max_length=100, verbose_name='Jabatan')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fungsionaris_photos/', verbose_name='Foto Fungsionaris')),
                ('urutan', models.IntegerField(default=0, verbose_name='Urutan Tampilan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('birdep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fungsionaris_set', to='birdep.birdep')),
            ],
            options={
                'verbose_name': 'Fungsionaris',
                'verbose_name_plural': 'Fungsionaris',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Program')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi Program')),
                ('urutan', models.IntegerField(default=0, verbose_name='Urutan Tampilan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('birdep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='birdep.birdep')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['urutan', 'judul'],
            },
        ),
    ]
