# Generated by Django 5.2 on 2025-08-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengurusInti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('jabatan', models.CharField(choices=[('dewan-pertimbangan', 'Dewan Pertimbangan'), ('ketua', 'Ketua'), ('wakil-ketua', 'Wakil Ketua'), ('sekretaris', 'Sekretaris'), ('bendahara', 'Bendahara'), ('koordinator-bidang-internal', 'Koordinator Bidang Internal'), ('koordinator-bidang-syiar', 'Koordinator Bidang Syiar'), ('koordinator-bidang-pembinaan-kaderisasi', 'Koordinator Bidang Pembinaan dan Kaderisasi'), ('koordinator-bidang-keuumatan', 'Koordinator Bidang Keuumatan'), ('koordinator-bidang-bisnis-teknologi', 'Koordinator Bidang Bisnis dan Teknologi'), ('koordinator-bidang-eksternal', 'Koordinator Bidang Eksternal')], max_length=50, verbose_name='Jabatan PI')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengurus_inti_photos/', verbose_name='Foto')),
                ('ikhtisar', models.TextField(help_text='Ringkasan singkat tentang pengurus', verbose_name='Ikhtisar')),
                ('deskripsi_kerja', models.TextField(help_text='Detail deskripsi kerja dan tanggung jawab', verbose_name='Deskripsi Kerja')),
                ('urutan', models.IntegerField(default=0, verbose_name='Urutan Tampilan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
            ],
            options={
                'verbose_name': 'Pengurus Inti',
                'verbose_name_plural': 'Pengurus Inti',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.RemoveField(
            model_name='birdep',
            name='tanggung_jawab',
        ),
        migrations.RemoveField(
            model_name='birdep',
            name='tugas',
        ),
        migrations.AddField(
            model_name='birdep',
            name='misi',
            field=models.TextField(blank=True, help_text='Misi dari BirDep', verbose_name='Misi'),
        ),
        migrations.AddField(
            model_name='birdep',
            name='nama_panjang',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nama Panjang BirDep'),
        ),
        migrations.AddField(
            model_name='birdep',
            name='visi',
            field=models.TextField(blank=True, help_text='Visi dari BirDep', verbose_name='Visi'),
        ),
        migrations.AlterField(
            model_name='birdep',
            name='nama',
            field=models.CharField(max_length=200, verbose_name='Nama Singkat BirDep'),
        ),
    ]
