# Generated by Django 6.1 on 2026-08-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdep', '0002_pengurusinti_remove_birdep_tanggung_jawab_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengurusinti',
            options={'ordering': ['kategori', 'urutan', 'nama'], 'verbose_name': 'Pengurus Inti', 'verbose_name_plural': 'Pengurus Inti'},
        ),
        migrations.AddField(
            model_name='pengurusinti',
            name='kategori',
            field=models.CharField(choices=[('pi', 'Pengurus Inti'), ('ki', 'Kontrol Internal'), ('mdc', 'Muslim Development Center')], default='pi', help_text='Menentukan halaman tempat pengurus ini ditampilkan', max_length=10, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='pengurusinti',
            name='deskripsi_kerja',
            field=models.TextField(blank=True, help_text='Detail deskripsi kerja dan tanggung jawab', verbose_name='Deskripsi Kerja'),
        ),
        migrations.AlterField(
            model_name='pengurusinti',
            name='ikhtisar',
            field=models.TextField(blank=True, help_text='Ringkasan singkat tentang pengurus', verbose_name='Ikhtisar'),
        ),
        migrations.AlterField(
            model_name='pengurusinti',
            name='jabatan',
            field=models.CharField(max_length=100, verbose_name='Jabatan'),
        ),
        migrations.AlterField(
            model_name='pengurusinti',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
