# Generated by Django 6.0.4 on 2026-08-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdep', '0003_alter_pengurusinti_options_pengurusinti_kategori_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birdep',
            options={'ordering': ['urutan', 'nama'], 'verbose_name': 'BirDep', 'verbose_name_plural': 'BirDeps'},
        ),
        migrations.AddField(
            model_name='birdep',
            name='urutan',
            field=models.IntegerField(default=0, help_text='Semakin kecil, semakin awal tampil di halaman Our Team', verbose_name='Urutan Tampilan'),
        ),
    ]
