# Generated by Django 6.0.4 on 2026-09-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdep', '0004_alter_birdep_options_birdep_urutan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fungsionaris',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='pengurusinti',
            name='foto',
        ),
        migrations.AddField(
            model_name='fungsionaris',
            name='foto_path',
            field=models.CharField(blank=True, default='', help_text='Path aset statis, mis. images/fungsionaris/lanang.jpg', max_length=150, verbose_name='Path Foto'),
        ),
        migrations.AddField(
            model_name='pengurusinti',
            name='foto_path',
            field=models.CharField(blank=True, default='', help_text='Path aset statis, mis. images/fungsionaris/lanang.jpg', max_length=150, verbose_name='Path Foto'),
        ),
    ]
